default:
  radiko_config :
    playlist_url : http://127.0.0.1:9000/radiko/
    # For normal mpd playlist
    playlist_file_mpd : /var/lib/mpd/playlists/00_radiko.m3u
    # For volumio playlist
    playlist_file_volumio : /data/playlist/Radiko
    pgdbname : radikopg.db

  # Account settings
  account :
    #mail : xxx@yyy.zzz
    #pass : foobarhogehoge

  system_config : 
    # Environment [MPD / VOLUMIO]
    tgt_env : VOLUMIO
    debug_mode : True
